name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 0 */3 * *'
jobs: 
    update-readme-with-blog: 
        name: "Update this repo's README with latest posts"
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://www.bcbrookman.com/feed.xml"
